### ISSUE TITLE
Merge changes back upstream?

### ISSUE THREAD

**Issue by poVoq** [Friskygote/matrix-discord-bridge#3]
Seems like this has some nice fixes that upstream would benefit from (and vise versa).

Any plans for that?

**Comment by Friskygote** [comment]
Interesting that I only found this issue now, but yeah, I'm nearing ending up my work here, just want to fix last few annoying issues. I generally work in a pretty slow pace so it takes me a while before getting everything done. Sorry for the wait 😅

**Comment by Friskygote** [comment]
Oh, also, I have a few personal changes in main branch, however I do not plan to merge those as those feel like very subjective in terms of being useful. The Matrix -> Discord parser however I hope to undraft upstream soon.
